# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stratt < Formula
  desc "A polyglot task runner that replaces Makefiles, manages release versions, and handles Kustomize image bumps."
  homepage "https://stratt.sh"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zebpalmer/stratt/releases/download/v0.4.0/stratt_0.4.0_darwin_amd64.tar.gz"
      sha256 "427c4be5ecb20405365387b9db7d469a8406a557e133f9d35bf33b4b30c2d6d9"

      define_method(:install) do
        bin.install "stratt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zebpalmer/stratt/releases/download/v0.4.0/stratt_0.4.0_darwin_arm64.tar.gz"
      sha256 "d2af8a6dd9c4ce23779cac27a7958607d65e740e7a029021d27c09d2f2d80fa6"

      define_method(:install) do
        bin.install "stratt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zebpalmer/stratt/releases/download/v0.4.0/stratt_0.4.0_linux_amd64.tar.gz"
      sha256 "6eebad7fbf215ac9810471ba9af896994856b593214dfb9965898210ac172178"
      define_method(:install) do
        bin.install "stratt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zebpalmer/stratt/releases/download/v0.4.0/stratt_0.4.0_linux_arm64.tar.gz"
      sha256 "341f5a1a052e7df48f6d2304dcd98767cfb11eb45e3e6436f844f36d9d9a558a"
      define_method(:install) do
        bin.install "stratt"
      end
    end
  end

  test do
    system "#{bin}/stratt version"
  end
end
